### ISSUE TITLE
postinstall script error

### ISSUE THREAD

**Issue by twiforce** [CyTube/mediaquery#1]
Well I was updating cytube and got this error after `npm install --no-bin-links`:

```
npm ERR! Linux 3.16.0-23-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! cytube-mediaquery@0.0.0 postinstall: `coffee -cmo lib src`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the cytube-mediaquery@0.0.0 postinstall script 'coffee -cmo lib src'.
```

Not sure that `-m` is really a parameter since `coffee -h` does not have any.
`--no-bin-links` here is because I'm running cytube on virtual machine which have NTFS filesystem which does not allow file locking and symlinks.

**Comment by calzoneman** [comment]
Do you have coffeescript installed at the global level?  The version in `package.json` is 1.9.1, for which the `-m` flag exists and is used to generate sourcemaps.  The only thing I can think of that might be happening is you have an old version of `coffee` in your `$PATH` and npm is calling that instead of the freshly installed version, since I have installed this successfully on various machines and various versions of node.

**Comment by calzoneman** [comment]
@twiforce Do you have any further comments on this?  If I don't hear from you within a few days, I'm going to go ahead and close it.
